nome = raw_input("Digite seu nome.:")
print('isalpha',nome.isalpha())
#print("isdecimal = ",nome.isdecimal())
print("isdigit = ",nome.isdigit())
#print("isnumeric = ",nome.isnumeric()) 
print("ISlower = ",nome.islower())
print("lower = ",nome.lower())
print("upper = ",nome.upper())
print("istitle = ",nome.istitle())
print("title = ",nome.title())
print("isspace = ",nome.isspace())
